services:
  ho-webserver:
    build:
      context: ./.docker/server_http/
      args:
        TIMEZONE: ${TIMEZONE}
    environment:
      - HOOS_CTF_EMAIL=${HOOS_CTF_EMAIL:-}
      - HOOS_CTF_USERNAME=${HOOS_CTF_USERNAME:-}
      - LANGUAGE=${LANGUAGE:-fr}
    labels:
      ho.ctf.cyrhades: "challenge"
      ho.ctf.cyrhades.bot: "1"
    ports:
      - ${PORT}:80
    restart: always
    volumes:
      - web:/var/www/html
  composer:
    image: composer
    volumes:
      - web:/app
    command: composer install --ignore-platform-req='ext-*'
volumes:
  web:
    labels:
      ho.ctf.cyrhades: "1"