<?php
	include((__DIR__.'/header.phtml'));
?>
<div style="text-align: center;">
    <h1>Nous contacter</h1>
    <div style="text-align: left;" class="alert alert-success">
        <strong>Vous avez trouvé un bogue ?</strong><br />
        Vous avez trouvé un bogue sur notre site? 
        Envoyez nous l'adresse, notre équipe technique analysera votre demande dans les plus brefs délais.
    </div>
    <form action="/contact" method="post">
        <label for="form_contact">Url : <input type="url" name="url" id="form_contact"></label>
        <button id="btn_contact" type="submit">Envoyer</button>
    </form>
</div>
<?php
	include((__DIR__.'/footer.phtml'));
?>