</div>

<div id="bg_top_footer">&nbsp;</div>
<footer class="foot">
    <div id="footer">
        <div id="bg_bottom">&nbsp;</div>
        <div id="foot_table">
        <table width="100%" cellspacing="0" cellpadding="0">
          <tr>
            <td width="180">
                <ul>
                    <li><a href="javascript:;" title="Aide">Besoin d'aide?</a></li>
                    <li><a href="javascript:;" title="Qui somme nous">Qui sommes nous</a></li>
                </ul>
            </td>
            <td width="350">
                <ul>
                    <li><a href="javascript:;" title="Catalogue en ligne">Catalogue</a></li>
                    <li><a href="javascript:;" rel="nofollow" title="Mon Compte">Mon Compte</a></li>
                </ul>
            </td>
            <td></td>
          </tr>
        </table>
        </div>
    </div>
</footer>
</div>
</body>
</html>