<?php
	include((__DIR__.'/header.phtml'));
?>
<div id="fil_ariane">
	Accueil > Notre sélection de T-shirts pour vous
</div>
{{FLAG}}
<div style="margin:10px">
	<div class="product-grid">
		<div class="product-item">
			<img src="/products/product_1.jpg" alt="Product 1">
			<h3>Polo Original L.12.12 coton petit piqué</h3>
			<p class="price">€110.00</p>
			<button class="add-to-cart">Ajouter au panier</button>
		</div>
		<div class="product-item">
			<img src="/products/product_2.jpg" alt="Product 2">
			<h3>T-shirt décontracté à col rond </h3>
			<p class="price">€29.99</p>
			<button class="add-to-cart">Ajouter au panier</button>
		</div>					
		<div class="product-item">
			<img src="/products/product_3.jpg" alt="Product 3">
			<h3>Tee Shirt Charing Noir</h3>
			<p class="price">€29.99</p>
			<button class="add-to-cart">Ajouter au panier</button>
		</div>

		<div class="product-item">
			<img src="/products/product_4.jpg" alt="Product 4">
			<h3>Tee Shirt Oversize Large Art Series Nounours Noir</h3>
			<p class="price">€29.00</p>
			<button class="add-to-cart">Ajouter au panier</button>
		</div>
		<div class="product-item">
			<img src="/products/product_5.jpg" alt="Product 5">
			<h3>Tee Shirt A6CBT Camel</h3>
			<p class="price">€29.99</p>
			<button class="add-to-cart">Ajouter au panier</button>
		</div>					
		<div class="product-item">
			<img src="/products/product_6.jpg" alt="Product 6">
			<h3>Tee Shirt Bicolore Avec Broderie 442 Camel Noir</h3>
			<p class="price">€29.99</p>
			<button class="add-to-cart">Ajouter au panier</button>
		</div>

		<div class="product-item">
			<img src="/products/product_7.jpg" alt="Product 7">
			<h3>Tee Shirt Oversize Large Art Series Marker Noir Vert Fluo</h3>
			<p class="price">€29.99</p>
			<button class="add-to-cart">Ajouter au panier</button>
		</div>					
		<div class="product-item">
			<img src="/products/product_8.jpg" alt="Product 8">
			<h3>Tee Shirt Oversize Large Art Series 2 Blanc</h3>
			<p class="price">€29.99</p>
			<button class="add-to-cart">Ajouter au panier</button>
		</div>
	</div>
</div>			
<?php
	include((__DIR__.'/footer.phtml'));
?>      